### ISSUE TITLE
EntityLevelChangeEvent jp.takesi.Mainでのnull

### ISSUE THREAD

**Issue by Takesikaityo** [Takesikaityo/EachWorld#1]
17:33:16 [CRITICAL] "'EachWorld v2.1.0'に'cn.nukkit.event.entity.EntityLevelChangeEvent'Eventを渡すことができませんでし た: jp.takesi.Mainでのnull"
17:33:16
         [ALERT] cn.nukkit.utils.EventException
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34)
        at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
        at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:568)
        at cn.nukkit.entity.Entity.switchLevel(Entity.java:1424)
        at cn.nukkit.Player.switchLevel(Player.java:875)
        at cn.nukkit.entity.Entity.setPosition(Entity.java:1768)
        at cn.nukkit.entity.Entity.setPositionAndRotation(Entity.java:1711)
        at cn.nukkit.entity.Entity.teleport(Entity.java:1901)
        at cn.nukkit.Player.teleport(Player.java:5013)
        at cn.nukkit.entity.Entity.teleport(Entity.java:1875)
        at cn.nukkit.entity.Entity.teleport(Entity.java:1871)
        at jp.takesi.Main.goLevel(Main.java:178)
        at jp.takesi.Main.onCommand(Main.java:215)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:299)
        at cn.nukkit.Server.dispatchCommand(Server.java:1101)
        at cn.nukkit.Player.handleDataPacket(Player.java:3384)
        at cn.nukkit.network.Network.processPackets(Network.java:260)
        at cn.nukkit.network.Network.processBatch(Network.java:231)
        at cn.nukkit.Player.handleDataPacket(Player.java:2272)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:158)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:67)
        at cn.nukkit.network.Network.processInterfaces(Network.java:155)
        at cn.nukkit.Server.tick(Server.java:1476)
        at cn.nukkit.Server.tickProcessor(Server.java:1274)
        at cn.nukkit.Server.start(Server.java:1253)
        at cn.nukkit.Server.<init>(Server.java:694)
        at cn.nukkit.Nukkit.main(Nukkit.java:82)
        Caused by: java.lang.Error: Unresolved compilation problems:
        メソッド sendMessage(String) は型 Entity で未定義です
        メソッド setGamemode(int) は型 Entity で未定義です

        at jp.takesi.Main.onLevelChange(Main.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
        ... 28 more

17:33:16 [CRITICAL] 
        コマンド'wo me'をwoで実行中に、処理できない例外が発生：java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at jp.takesi.Main.goLevel(Main.java:180)
        at jp.takesi.Main.onCommand(Main.java:215)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:299)
        at cn.nukkit.Server.dispatchCommand(Server.java:1101)
        at cn.nukkit.Player.handleDataPacket(Player.java:3384)
        at cn.nukkit.network.Network.processPackets(Network.java:260)
        at cn.nukkit.network.Network.processBatch(Network.java:231)
        at cn.nukkit.Player.handleDataPacket(Player.java:2272)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:158)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:67)
        at cn.nukkit.network.Network.processInterfaces(Network.java:155)
        at cn.nukkit.Server.tick(Server.java:1476)
        at cn.nukkit.Server.tickProcessor(Server.java:1274)
        at cn.nukkit.Server.start(Server.java:1253)
        at cn.nukkit.Server.<init>(Server.java:694)
        at cn.nukkit.Nukkit.main(Nukkit.java:82)

17:33:16 [ALERT]
         java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
        at jp.takesi.Main.goLevel(Main.java:180)
        at jp.takesi.Main.onCommand(Main.java:215)
        at cn.nukkit.command.PluginCommand.execute(PluginCommand.java:33)
        at cn.nukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:299)
        at cn.nukkit.Server.dispatchCommand(Server.java:1101)
        at cn.nukkit.Player.handleDataPacket(Player.java:3384)
        at cn.nukkit.network.Network.processPackets(Network.java:260)
        at cn.nukkit.network.Network.processBatch(Network.java:231)
        at cn.nukkit.Player.handleDataPacket(Player.java:2272)
        at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:158)
        at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:123)
        at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:67)
        at cn.nukkit.network.Network.processInterfaces(Network.java:155)
        at cn.nukkit.Server.tick(Server.java:1476)
        at cn.nukkit.Server.tickProcessor(Server.java:1274)
        at cn.nukkit.Server.start(Server.java:1253)
        at cn.nukkit.Server.<init>(Server.java:694)
        at cn.nukkit.Nukkit.main(Nukkit.java:82)

**Comment by Megapix96** [comment]
(Player)
キャストしてね❤️

**Comment by Takesikaityo** [comment]
つまり (Player) をつければいいのかな？
